const products=[
 {id:1,name:'Telegram Premium — 12 месяцев',cat:'Подписки',price:2490,rating:4.9,stock:127,icon:'TG',tone:'#149bd7',brand:'#149bd7',hot:true,sales:980},
 {id:2,name:'Steam Gift Card — 1 000 ₽',cat:'Игры',price:1090,rating:4.8,stock:84,icon:'ST',tone:'#16283b',brand:'#142233',hot:true,sales:850},
 {id:3,name:'VPN Unlimited — 1 год',cat:'Сервисы',price:790,rating:4.7,stock:312,icon:'V',tone:'#ec173c',brand:'#ec173c',sales:760},
 {id:4,name:'Spotify Premium — 6 месяцев',cat:'Подписки',price:990,rating:4.9,stock:45,icon:'SP',tone:'#18a94b',brand:'#18a94b',hot:true,sales:920},
 {id:5,name:'Windows 11 Pro — ключ активации',cat:'Софт',price:1290,rating:4.8,stock:205,icon:'W',tone:'#2589e8',brand:'#2589e8',sales:680},
 {id:6,name:'Discord Nitro — 1 месяц',cat:'Подписки',price:549,rating:4.7,stock:98,icon:'DS',tone:'#5864ee',brand:'#5864ee',sales:650},
 {id:7,name:'PlayStation Store — 2 500 ₽',cat:'Игры',price:2690,rating:4.9,stock:36,icon:'PS',tone:'#1262c7',brand:'#1262c7',sales:610},
 {id:8,name:'Residential Proxy — 10 GB',cat:'Сервисы',price:1590,rating:4.6,stock:500,icon:'PX',tone:'#ee632d',brand:'#ee632d',sales:570},
 {id:9,name:'Adobe Creative Cloud — 3 месяца',cat:'Софт',price:1890,rating:4.8,stock:73,icon:'A',tone:'#d52135',brand:'#d52135',sales:540},
 {id:10,name:'Xbox Game Pass Ultimate — 3 мес.',cat:'Игры',price:1490,rating:4.7,stock:67,icon:'X',tone:'#18853b',brand:'#18853b',sales:510},
 {id:11,name:'YouTube Premium — 12 месяцев',cat:'Подписки',price:1390,rating:4.9,stock:102,icon:'YT',tone:'#f01928',brand:'#f01928',sales:800},
 {id:12,name:'ChatGPT Plus — 1 месяц',cat:'Сервисы',price:2290,rating:4.8,stock:54,icon:'AI',tone:'#111',brand:'#111',sales:720}
];
let active='Все',cart=JSON.parse(localStorage.getItem('sous-cart')||'[]');
const $=s=>document.querySelector(s), grid=$('#productGrid');
const money=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
function renderCategories(){const cats=['Все',...new Set(products.map(p=>p.cat))];$('#categories').innerHTML=cats.map(c=>`<button class="${c===active?'active':''}" data-cat="${c}">${c}</button>`).join('');}
function render(){let list=products.filter(p=>(active==='Все'||p.cat===active)&&p.name.toLowerCase().includes($('#searchInput').value.toLowerCase()));const sort=$('#sortSelect').value;list.sort((a,b)=>sort==='cheap'?a.price-b.price:sort==='expensive'?b.price-a.price:sort==='rating'?b.rating-a.rating:b.sales-a.sales);grid.innerHTML=list.map(p=>`<article class="product" data-id="${p.id}"><div class="product-visual" style="--tone:${p.tone};--brand:${p.brand}">${p.hot?'<span class="tag">HOT DROP</span>':''}<button class="wish" aria-label="В избранное">♡</button><div class="product-icon">${p.icon}</div></div><div class="product-body"><span class="product-cat">${p.cat.toUpperCase()}</span><h3>${p.name}</h3><div class="rating"><strong>★</strong> ${p.rating} <span class="stock">в наличии ${p.stock}</span></div><div class="product-bottom"><span class="price">${money(p.price)}</span><button class="add" data-add="${p.id}" aria-label="В корзину">+</button></div></div></article>`).join('');$('#emptyState').classList.toggle('show',!list.length)}
function saveCart(){localStorage.setItem('sous-cart',JSON.stringify(cart));updateCart()}
function add(id){const item=cart.find(x=>x.id===id);item?item.qty++:cart.push({id,qty:1});saveCart();toast('Товар добавлен в корзину')}
function updateCart(){const items=cart.map(x=>({...products.find(p=>p.id===x.id),qty:x.qty}));$('#cartCount').textContent=items.reduce((s,x)=>s+x.qty,0);$('#cartItems').innerHTML=items.map(p=>`<div class="cart-item"><div class="mini" style="background:${p.tone}">${p.icon}</div><div><b>${p.name}</b><span>${p.qty} × ${money(p.price)}</span></div><button class="remove" data-remove="${p.id}">×</button></div>`).join('');$('#cartEmpty').style.display=items.length?'none':'grid';$('#cartTotal').style.display=items.length?'block':'none';$('#totalPrice').textContent=money(items.reduce((s,x)=>s+x.price*x.qty,0))}
function openCart(){closeModal();$('#drawer').classList.add('open');$('#overlay').classList.add('show');document.body.style.overflow='hidden'}
function closeAll(){$('#drawer').classList.remove('open');closeModal();$('#overlay').classList.remove('show');document.body.style.overflow='';}
function showProduct(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-product"><div class="modal-visual" style="--tone:${p.tone}">${p.icon}</div><div class="modal-info"><span class="product-cat">${p.cat.toUpperCase()}</span><h3>${p.name}</h3><div class="rating"><strong>★</strong> ${p.rating} · ${p.sales} покупок</div><p>Проверенный цифровой товар с автоматической выдачей сразу после оплаты. Инструкция и данные появятся в личном кабинете.</p><div class="modal-meta"><span>⚡ Моментально</span><span>✓ Гарантия 24 ч.</span><span>◈ Безопасно</span></div><div class="modal-buy"><b class="price">${money(p.price)}</b><button class="primary" data-add="${p.id}">В корзину <span>→</span></button></div></div></div>`;$('#productModal').classList.add('show');$('#overlay').classList.add('show');document.body.style.overflow='hidden'}
function closeModal(){$('#productModal').classList.remove('show')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove('show'),2200)}
renderCategories();render();updateCart();
$('#categories').onclick=e=>{if(e.target.dataset.cat){active=e.target.dataset.cat;renderCategories();render()}};$('#searchInput').oninput=render;$('#sortSelect').onchange=render;
document.addEventListener('click',e=>{const addBtn=e.target.closest('[data-add]');if(addBtn){e.stopPropagation();add(+addBtn.dataset.add);return}const card=e.target.closest('.product');if(card&&!e.target.closest('.wish'))showProduct(+card.dataset.id);if(e.target.dataset.remove){cart=cart.filter(x=>x.id!==+e.target.dataset.remove);saveCart()}if(e.target.closest('[data-toast]'))toast(e.target.closest('[data-toast]').dataset.toast)});
$('#cartBtn').onclick=openCart;$('#closeCart').onclick=closeAll;$('#overlay').onclick=closeAll;$('.modal-close').onclick=closeAll;$('#checkout').onclick=()=>toast('Демо: подключите платёжный провайдер');$('#playBtn').onclick=()=>$('#how').scrollIntoView();
const faq=[['Как быстро я получу товар?','Большинство товаров выдаются автоматически в течение нескольких секунд после подтверждения оплаты.'],['Что делать, если товар не подошёл?','Откройте обращение в течение гарантийного срока — поддержка проверит заказ и предложит замену.'],['Какие способы оплаты доступны?','Интерфейс подготовлен для подключения карт, СБП и криптовалюты. Конкретные методы зависят от платёжного провайдера.'],['Это безопасно?','Заказы и действия пользователя должны передаваться только по HTTPS; платёжные данные обрабатывает сертифицированный провайдер.']];
$('#accordions').innerHTML=faq.map(([q,a],i)=>`<div class="accordion ${i===0?'open':''}"><button class="acc-btn">${q}<i>+</i></button><div class="acc-content">${a}</div></div>`).join('');$('#accordions').onclick=e=>{const a=e.target.closest('.accordion');if(a)a.classList.toggle('open')};
const art=$('#heroArt');if(art)window.addEventListener('mousemove',e=>{const x=(e.clientX/innerWidth-.5)*12,y=(e.clientY/innerHeight-.5)*-12;$('.hero-card').style.transform=`rotate(5deg) rotateY(${x}deg) rotateX(${y}deg)`});

--- EXIT 0 ---
