const tg=window.Telegram?.WebApp;tg?.ready();tg?.expand();tg?.setHeaderColor('#08131f');tg?.setBackgroundColor('#08131f');
const state={services:[],countries:[],prices:[],service:null,country:null,activation:null,balance:0,profile:null,user:null,provider:'xrocket',servicePage:1,countryPage:1,pricePage:1,pageSize:16,cancelTimer:null,cancelRemaining:0};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const initData=tg?.initData||''; const apiBase=`api`;
const colors=['#4478e8','#ff4b55','#1dcf70','#e05acb','#ff9d38','#7167ec','#23a3c7'];
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(text){const x=$('#toast');x.textContent=text;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),3000);tg?.HapticFeedback?.notificationOccurred('error')}
function loading(on){$('#loader').classList.toggle('hidden',!on)}
function apiErrorMessage(data,status){
  const values=[data?.message,data?.error,data?.detail,data?.details,data?.code].filter(x=>typeof x==='string'&&x.trim()).map(x=>x.trim());
  const raw=values.join(' ');
  // API may return internal identifiers as the message (for example
  // "business_logic.OFFER_NOT_FOUND"). Only show actual localized prose.
  const localized=values.find(x=>/[А-Яа-яЁё]/.test(x)&&!/(?:business_logic|internal_error|traceback|exception)[.:_\s-]/i.test(x));
  if(localized)return localized;
  if(/(?:business_logic[.:_\s-]*)?offer[_\s.-]*not[_\s.-]*found/i.test(raw))return 'Выбранный тариф больше недоступен. Выберите другой тариф.';
  if(status===401||status===403)return 'Не удалось подтвердить сессию Telegram. Перезапустите приложение.';
  if(status===429)return 'Слишком много запросов. Попробуйте немного позже.';
  return status>=500?'Сервис временно недоступен. Попробуйте позже.':'Не удалось выполнить запрос. Попробуйте ещё раз.';
}
async function api(path,options={}){
  let r;
  try{r=await fetch(`${apiBase}${path}`,{...options,headers:{'Content-Type':'application/json','X-Telegram-Init-Data':initData,...options.headers}})}
  catch(_error){throw new Error('Нет соединения с сервером. Проверьте интернет и попробуйте снова.')}
  const data=await r.json().catch(()=>({}));
  if(!r.ok)throw new Error(apiErrorMessage(data,r.status));
  return data
}
function money(v){return `$${Number(v||0).toFixed(2)}`}
function setBalance(v){state.balance=Number(v||0);$('#balanceButton').textContent=money(v)}
const serviceMarks={fb:'f',go:'G',am:'a',ig:'◎',wa:'☎',lf:'♪',tg:'➤',dr:'AI',ka:'S',vk:'VK',tw:'X',ds:'◈',mm:'M',ot:'OK',ub:'U',nf:'N',sp:'S'};
const serviceIcons={fb:'facebook',go:'google',am:'amazon',ig:'instagram',wa:'whatsapp',lf:'tiktok',tg:'telegram',dr:'openai',ka:'shopee',vk:'vk',tw:'x',ds:'discord',mm:'microsoft',ub:'uber',nf:'netflix',sp:'spotify',ya:'yandexcloud',av:'avast',wb:'wildberries',oz:'ozon',li:'linkedin',pi:'pinterest',sn:'snapchat',dp:'dropbox',mb:'airbnb',mt:'steam',we:'wechat',vi:'viber',ok:'odnoklassniki',tn:'tinder',ki:'kik',sl:'slack',sk:'skype',zo:'zoom',gh:'github',gt:'gitlab',tk:'tokopedia',fu:'foursquare',im:'imo',dc:'doordash',ab:'alibabadotcom',ae:'aliexpress',eb:'ebay',pp:'paypal',bm:'bumble'};
const countryFlags={Russia:'🇷🇺',Ukraine:'🇺🇦',Kazakhstan:'🇰🇿',China:'🇨🇳',Philippines:'🇵🇭',Myanmar:'🇲🇲',Indonesia:'🇮🇩',Malaysia:'🇲🇾',Kenya:'🇰🇪',Tanzania:'🇹🇿',Vietnam:'🇻🇳',Kyrgyzstan:'🇰🇬','United States':'🇺🇸',USA:'🇺🇸',Israel:'🇮🇱','Hong Kong':'🇭🇰',Poland:'🇵🇱','United Kingdom':'🇬🇧',England:'🇬🇧',Madagascar:'🇲🇬',Nigeria:'🇳🇬',Macau:'🇲🇴',Egypt:'🇪🇬',India:'🇮🇳',Ireland:'🇮🇪',Cambodia:'🇰🇭',Laos:'🇱🇦',Haiti:'🇭🇹','Ivory Coast':'🇨🇮',Gambia:'🇬🇲',Serbia:'🇷🇸',Yemen:'🇾🇪','South Africa':'🇿🇦',Romania:'🇷🇴',Colombia:'🇨🇴',Estonia:'🇪🇪',Azerbaijan:'🇦🇿',Canada:'🇨🇦',Morocco:'🇲🇦',Ghana:'🇬🇭',Argentina:'🇦🇷',Uzbekistan:'🇺🇿',Cameroon:'🇨🇲',Chad:'🇹🇩',Germany:'🇩🇪',Lithuania:'🇱🇹',Croatia:'🇭🇷',Sweden:'🇸🇪',Iraq:'🇮🇶',Netherlands:'🇳🇱',Latvia:'🇱🇻',Austria:'🇦🇹',Belarus:'🇧🇾',Thailand:'🇹🇭',SaudiArabia:'🇸🇦',Mexico:'🇲🇽',Taiwan:'🇹🇼',Spain:'🇪🇸',Iran:'🇮🇷',Algeria:'🇩🇿',Slovenia:'🇸🇮',Bangladesh:'🇧🇩',Senegal:'🇸🇳',Turkey:'🇹🇷',Czech:'🇨🇿',Brazil:'🇧🇷',Portugal:'🇵🇹',France:'🇫🇷',Moldova:'🇲🇩',Italy:'🇮🇹'};
function serviceLogo(item,index){const mark=serviceMarks[item.id]||(item.name||'?').replace(/[^A-Za-zА-Яа-я0-9]/g,'').slice(0,2).toUpperCase();const slug=serviceIcons[item.id];return slug?`<span class="service-logo"><img class="brand-img" src="https://cdn.simpleicons.org/${slug}" alt=""><span class="brand-fallback" style="color:${colors[index%colors.length]}">${escapeHtml(mark)}</span></span>`:`<span class="service-logo fallback"><span class="brand-fallback" style="color:${colors[index%colors.length]}">${escapeHtml(mark)}</span></span>`}
function countryLogo(item){const eng=String(item.title?.eng||'');const initials=eng.replace(/[^A-Za-z ]/g,'').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();const iso=/^[a-z]{2}$/.test(item.iso||'')?item.iso:'';return iso?`<span class="country-logo"><img src="https://flagcdn.com/w80/${iso}.png" alt="${escapeHtml(eng)}"></span>`:`<span class="country-logo initials">${escapeHtml(initials)}</span>`}
function hydrateLogos(){document.querySelectorAll('.brand-img').forEach(img=>img.onerror=()=>img.parentElement.classList.add('fallback'))}
function pager(id,page,total){const box=$(id),pages=Math.max(1,Math.ceil(total/state.pageSize));page=Math.min(page,pages);box.querySelector('span').textContent=`${page} / ${pages}`;box.querySelector('[data-page="prev"]').disabled=page<=1;box.querySelector('[data-page="next"]').disabled=page>=pages}
function screen(id){$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('nav [data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===id));$('#backButton').style.visibility=['countriesScreen','pricesScreen','activationScreen'].includes(id)?'visible':'hidden';scrollTo(0,0)}
const searchCharMap={а:'a',б:'b',в:'v',г:'g',д:'d',е:'e',ё:'e',ж:'zh',з:'z',и:'i',й:'i',к:'k',л:'l',м:'m',н:'n',о:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ф:'f',х:'h',ц:'c',ч:'ch',ш:'sh',щ:'sh',ы:'y',э:'e',ю:'yu',я:'ya',ь:'',ъ:''};
function normalizeSearch(v){return Array.from(String(v||'').toLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g,'')).map(c=>Object.prototype.hasOwnProperty.call(searchCharMap,c)?searchCharMap[c]:c).join('').replace(/instagram|instgram|insta|threads/g,' instagram ').replace(/[^a-z0-9]+/g,' ').trim()}
function searchDistance(a,b){const r=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let p=r[0];r[0]=i;for(let j=1;j<=b.length;j++){const s=r[j];r[j]=Math.min(r[j]+1,r[j-1]+1,p+(a[i-1]===b[j-1]?0:1));p=s}}return r[b.length]}
function searchScore(value,query){const q=normalizeSearch(query),v=normalizeSearch(value);if(!q)return 1;if(v===q)return 1000;if(v.startsWith(q))return 800-v.length;if(v.includes(q))return 600-v.indexOf(q);const qs=q.split(' '),vs=v.split(' ');let total=0;for(const token of qs){let best=0;for(const candidate of vs){if(candidate.startsWith(token)||token.startsWith(candidate))best=Math.max(best,80);const d=searchDistance(token,candidate),allowed=Math.max(token.length,candidate.length)>=7?2:1;if(d<=allowed)best=Math.max(best,70-d*10)}if(!best)return 0;total+=best}return total}
function serviceSearchValue(x){const aliases={ig:'instagram instgram insta threads инстаграм инста',fb:'facebook фейсбук',tg:'telegram телеграм',wa:'whatsapp ватсап вотсап',go:'google youtube gmail гугл ютуб почта',lf:'tiktok тикток',vk:'vkontakte вконтакте вк'};return `${x.name||''} ${x.id||''} ${aliases[x.id]||''}`}
function renderServices(filter=$('#serviceSearch').value){const all=state.services.map(x=>({x,score:searchScore(serviceSearchValue(x),filter)})).filter(row=>row.score>0).sort((a,b)=>b.score-a.score||String(a.x.name||'').localeCompare(String(b.x.name||''),'ru')).map(row=>row.x);const start=(state.servicePage-1)*state.pageSize,rows=all.slice(start,start+state.pageSize);$('#serviceList').innerHTML=rows.map((x,i)=>`<button class="row" data-service="${escapeHtml(x.id)}">${serviceLogo(x,start+i)}<span class="row-text"><span class="row-title">${escapeHtml(x.name)}</span></span><span class="chevron">›</span></button>`).join('')||'<div class="empty">Не найдено</div>';pager('#servicePager',state.servicePage,all.length);hydrateLogos()}
function renderCountries(filter=$('#countrySearch').value){const all=state.countries.map(x=>({x,score:searchScore(`${x.title?.rus||''} ${x.title?.eng||''} ${x.iso||''}`,filter)})).filter(row=>row.score>0).sort((a,b)=>b.score-a.score).map(row=>row.x);const start=(state.countryPage-1)*state.pageSize,rows=all.slice(start,start+state.pageSize);$('#countryList').innerHTML=rows.map(x=>`<button class="row" data-country="${Number(x.id)||0}">${countryLogo(x)}<span class="row-text"><span class="row-title">${escapeHtml(x.title?.rus||x.title?.eng)}</span></span><span class="chevron">›</span></button>`).join('')||'<div class="empty">Не найдено</div>';pager('#countryPager',state.countryPage,all.length)}
function activationRow(x){const status={waiting:'Ожидание',code_received:`Код: ${x.sms_code}`,finished:'Готово',canceled:'Отменено',ordering:'Создаётся'}[x.status]||x.status;return `<button class="row" data-activation="${Number(x.id)||0}">${serviceLogo({id:x.service_id,name:x.service_name},Number(x.id)||0)}<span class="row-text"><span class="row-title">${escapeHtml(x.service_name)} · ${escapeHtml(x.country_name)}</span><span class="row-sub">${escapeHtml(x.phone||'')} ${escapeHtml(status)}</span></span><b>${money(x.sale_price_usd)}</b></button>`}
async function bootstrap(){loading(true);try{const d=await api('/bootstrap');state.services=d.services||[];state.countries=d.countries||[];if(d.provider_error)toast(d.provider_error);state.profile=d.profile;state.user=d.user;setBalance(d.profile.balance);$('#supportLink').href=d.support_url||'#';$('#profileSupport').href=d.support_url||'#';renderServices();renderCountries();renderHistory(d.activations);renderProfile(d)}catch(e){toast(e.message)}finally{loading(false)}}
function renderProfile(d){const u=d.user||state.user||{};const p=d.profile||state.profile||{};const name=[u.first_name,u.last_name].filter(Boolean).join(' ')||u.username||'Пользователь';$('#profileName').textContent=name;$('#profileId').textContent=`ID ${u.id||p.user_id||'—'}`;$('#profileAvatar').textContent=name.slice(0,1).toUpperCase();$('#profileBalance').textContent=money(p.balance);$('#activationCount').textContent=(d.activations||[]).length;$('#topupsTotal').textContent=money(p.topups_total)}
function renderHistory(items){$('#historyList').innerHTML=items.length?items.map(activationRow).join(''):'<div class="empty">Активаций пока нет</div>'}
function renderPrices(){const start=(state.pricePage-1)*state.pageSize,rows=state.prices.slice(start,start+state.pageSize);$('#priceList').innerHTML=rows.length?rows.map(x=>`<button class="row" data-provider="${x.provider_id}" data-price="${x.supplier_price_rub}" data-sale="${x.sale_price_usd}"><span class="logo" style="--logo:#282a35">⚡</span><span class="row-text"><span class="row-title">Тариф</span><span class="stock">В наличии: ${x.count}</span></span><span><div class="price">${money(x.sale_price_usd)}</div><div class="stock">${x.supplier_price_rub.toFixed(2)} ₽</div></span></button>`).join(''):'<div class="empty">Нет номеров</div>';pager('#pricePager',state.pricePage,state.prices.length)}
async function loadPrices(){loading(true);try{const d=await api(`/prices?service=${encodeURIComponent(state.service.id)}&country=${state.country.id}`);state.prices=d.prices;state.pricePage=1;renderPrices();screen('pricesScreen')}catch(e){toast(e.message)}finally{loading(false)}}
async function buy(provider,price,sale){if(!confirm(`Купить за ${money(sale)}?`))return;loading(true);try{const d=await api('/order',{method:'POST',body:JSON.stringify({request_key:crypto.randomUUID(),service:state.service.id,service_name:state.service.name,country:state.country.id,country_name:state.country.title.rus||state.country.title.eng,provider_id:Number(provider),supplier_price_rub:Number(price)})});state.activation=d.activation;setBalance(d.profile.balance);showActivation(d.activation);tg?.HapticFeedback?.notificationOccurred('success')}catch(e){toast(e.message)}finally{loading(false)}}
function updateCancelButton(){const b=$('#cancelActivation'),terminal=['canceled','finished','code_received'].includes(state.activation?.status);if(terminal){b.disabled=true;b.textContent='Отменить';return}if(state.cancelRemaining>0){const m=Math.floor(state.cancelRemaining/60),s=state.cancelRemaining%60;b.disabled=true;b.textContent=`Отмена через ${m}:${String(s).padStart(2,'0')}`;state.cancelRemaining--}else{b.disabled=false;b.textContent='Отменить'}}
function showActivation(a){state.activation=a;$('#phone').textContent=a.phone?`+${String(a.phone).replace(/^\+/,'')}`:'—';$('#smsCode').textContent=a.sms_code||'';$('#smsCode').classList.toggle('hidden',!a.sms_code);$('#activationStatus').textContent=a.sms_code?'Код получен ✅':a.status==='canceled'?'Активация отменена':'Ожидаем SMS-код…';clearInterval(state.cancelTimer);state.cancelRemaining=Number(a.cancel_after_seconds||0);updateCancelButton();state.cancelTimer=setInterval(updateCancelButton,1000);screen('activationScreen')}
async function action(name){if(!state.activation)return;loading(true);try{const d=await api(`/activations/${state.activation.id}/${name}`,{method:'POST',body:'{}'});state.activation=d.activation;setBalance(d.profile?.balance??state.balance);showActivation(d.activation);if(name==='cancel')toast(d.refunded?'Деньги возвращены на баланс':'Активация отменена')}catch(e){toast(e.message)}finally{loading(false)}}
$('#serviceSearch').oninput=e=>{state.servicePage=1;renderServices(e.target.value)};$('#countrySearch').oninput=e=>{state.countryPage=1;renderCountries(e.target.value)};
$('#serviceList').onclick=e=>{const b=e.target.closest('[data-service]');if(!b)return;state.service=state.services.find(x=>x.id===b.dataset.service);$('#selectedService').textContent=`Сервис: ${state.service.name}`;screen('countriesScreen')};
$('#countryList').onclick=e=>{const b=e.target.closest('[data-country]');if(!b)return;state.country=state.countries.find(x=>x.id===Number(b.dataset.country));$('#selectedCountry').textContent=`${state.service.name} · ${state.country.title.rus||state.country.title.eng}`;loadPrices()};
$('#priceList').onclick=e=>{const b=e.target.closest('[data-provider]');if(b)buy(b.dataset.provider,b.dataset.price,b.dataset.sale)};
$('#historyList').onclick=e=>{const b=e.target.closest('[data-activation]');if(b){api(`/activations/${b.dataset.activation}`).then(d=>showActivation(d.activation)).catch(x=>toast(x.message))}};
$('#checkCode').onclick=()=>action('check');$('#newCode').onclick=()=>action('new-code');$('#cancelActivation').onclick=()=>confirm('Отменить активацию и запросить возврат?')&&action('cancel');$('#phone').onclick=()=>navigator.clipboard.writeText($('#phone').textContent).then(()=>toast('Номер скопирован'));
$('#backButton').onclick=()=>screen($('#pricesScreen').classList.contains('active')?'countriesScreen':$('#countriesScreen').classList.contains('active')?'servicesScreen':'historyScreen');
function openTopup(){state.provider='xrocket';$$('.providers button').forEach(x=>x.classList.toggle('active',x.dataset.provider==='xrocket'));$('#topupSheet').classList.remove('hidden');$('#topupAmount').focus()}
function closeTopup(){$('#topupSheet').classList.add('hidden')}
$('#balanceButton').onclick=openTopup;$('#profileTopup').onclick=openTopup;$('#closeTopup').onclick=closeTopup;$('#topupSheet').onclick=e=>{if(e.target===$('#topupSheet'))closeTopup()};
$$('.providers button').forEach(x=>x.onclick=()=>{state.provider=x.dataset.provider;$$('.providers button').forEach(b=>b.classList.toggle('active',b===x))});
$('#createTopup').onclick=async()=>{const amount=Number($('#topupAmount').value);if(!(amount>=1))return toast('Минимум $1');const b=$('#createTopup');b.disabled=true;loading(true);try{const d=await api('/topup',{method:'POST',body:JSON.stringify({amount,provider:state.provider})});if(!d.pay_url)throw new Error('Нет ссылки');closeTopup();tg?.openLink?tg.openLink(d.pay_url):window.open(d.pay_url,'_blank','noopener')}catch(e){toast(e.message)}finally{b.disabled=false;loading(false)}};
$('#servicePager').onclick=e=>{const d=e.target.dataset.page;if(!d)return;state.servicePage+=d==='next'?1:-1;renderServices();scrollTo(0,0)};
$('#countryPager').onclick=e=>{const d=e.target.dataset.page;if(!d)return;state.countryPage+=d==='next'?1:-1;renderCountries();scrollTo(0,0)};
$('#pricePager').onclick=e=>{const d=e.target.dataset.page;if(!d)return;state.pricePage+=d==='next'?1:-1;renderPrices();scrollTo(0,0)};
$$('nav [data-nav]').forEach(x=>x.onclick=async()=>{if(x.dataset.nav==='historyScreen'){loading(true);try{const d=await api('/activations');renderHistory(d.items);screen('historyScreen')}catch(e){toast(e.message)}finally{loading(false)}}else screen(x.dataset.nav)});
bootstrap();

